export const FETCH_RELEASES_START = 'FETCH_RELEASES_START';
export const FETCH_RELEASES_SUCESS = 'FETCH_RELEASES_SUCESS';
export const FETCH_RELEASES_ERROR = 'FETCH_RELEASES_ERROR';

export const FETCH_STORIES_START = 'FETCH_STORIES_START';
export const FETCH_STORIES_SUCESS = 'FETCH_STORIES_SUCESS';
export const FETCH_STORIES_ERROR = 'FETCH_STORIES_ERROR';
